[tool.poetry]
name = "peeweeplayground"
version = "0.1.0"
description = ""
authors = ["Luciano Filho <lvgalvaofilho@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
peewee = "^3.16.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
